// Objective-C API for talking to github.com/EducationEKT/EKT/mobile Go package.
//   gobind -lang=objc github.com/EducationEKT/EKT/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "Universe.objc.h"


@class MobileEncryptPrivateKey;
@class MobileKeyStore;

@interface MobileEncryptPrivateKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (long)version;
- (void)setVersion:(long)v;
- (NSString*)encryptData;
- (void)setEncryptData:(NSString*)v;
@end

@interface MobileKeyStore : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)address;
- (void)setAddress:(NSString*)v;
// skipped field KeyStore.PrivateKey with unsupported type: github.com/EducationEKT/EKT/mobile.EncryptPrivateKey

@end

FOUNDATION_EXPORT NSString* MobileCreateKeyStore(NSString* key, NSString* auth);

FOUNDATION_EXPORT NSString* MobileDecryptKeystore(NSString* keystore, NSString* auth);

FOUNDATION_EXPORT NSString* MobileGetAccount(void);

FOUNDATION_EXPORT NSData* MobileGetPubKeyFromPrivKey(NSData* priv, NSError** error);

FOUNDATION_EXPORT NSString* MobilePrivKey2Address(NSString* priv);

FOUNDATION_EXPORT NSData* MobilePubKey2Address(NSData* pubKey);

FOUNDATION_EXPORT NSData* MobileRecoverPubKey(NSData* msg, NSData* sign, NSError** error);

FOUNDATION_EXPORT NSData* MobileSha3_256(NSData* data);

FOUNDATION_EXPORT NSData* MobileSign(NSData* msg, NSData* privKey, NSError** error);

FOUNDATION_EXPORT NSString* MobileSignMsg(NSString* data, NSString* privKey);

#endif
